name: Cypress Tests
on: [push]
jobs:
  pre-test:
    name: Cypress setup
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.17.6-chrome100-ff98
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install  
        uses: cypress-io/github-action@v3
        with:
          runTests: false

  test:
    name: Cypress run
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.17.6-chrome100-ff98
    needs: pre-test
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Cypress screenshots
          path: cypress/screenshots
      
     
     
 

